//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionDetail
    {
        public int OptionDetailsId { get; set; }
        public int QuesDetailId { get; set; }
        public string OpOne { get; set; }
        public string OpTwo { get; set; }
        public string OpThree { get; set; }
        public string OpFour { get; set; }
        public bool Active { get; set; }
    
        public virtual QuesDetail QuesDetail { get; set; }
    }
}
