//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuesDetail
    {
        public QuesDetail()
        {
            this.OptionDetails = new HashSet<OptionDetail>();
            this.ScoreDetails = new HashSet<ScoreDetail>();
        }
    
        public int QuesDetailId { get; set; }
        public int SubTopicId { get; set; }
        public string Question { get; set; }
        public string OpCorrect { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<OptionDetail> OptionDetails { get; set; }
        public virtual SubTopic SubTopic { get; set; }
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
    }
}
