//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreDetail
    {
        public int ScoreDetailsId { get; set; }
        public int UserId { get; set; }
        public int Attempted { get; set; }
        public int Corrected { get; set; }
        public System.DateTime date { get; set; }
        public decimal Score { get; set; }
        public bool Active { get; set; }
        public int QuesDetailId { get; set; }
        public string Duration { get; set; }
        public Nullable<int> SubID { get; set; }
    
        public virtual QuesDetail QuesDetail { get; set; }
        public virtual user user { get; set; }
    }
}
