//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Stud_ProgTest_Ans
    {
        public Tbl_Stud_ProgTest_Ans()
        {
            this.PerTestCaseResults = new HashSet<PerTestCaseResult>();
        }
    
        public int Stud_Ans_ID { get; set; }
        public int Stud_ID { get; set; }
        public int Ques_ID { get; set; }
        public int Test_ID { get; set; }
        public string Stud_Ans { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Score_id { get; set; }
        public decimal Marks { get; set; }
        public Nullable<int> Prog_Langid { get; set; }
    
        public virtual ICollection<PerTestCaseResult> PerTestCaseResults { get; set; }
        public virtual Tbl_Prog_Ques Tbl_Prog_Ques { get; set; }
        public virtual Tbl_Stud_ProgTest_Result Tbl_Stud_ProgTest_Result { get; set; }
        public virtual Tbl_Stud_ProgTest_Result Tbl_Stud_ProgTest_Result1 { get; set; }
        public virtual Tbl_Stud_ProgTest_Result Tbl_Stud_ProgTest_Result2 { get; set; }
        public virtual Tbl_Stud_ProgTest_Result Tbl_Stud_ProgTest_Result3 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
