//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Prog_Test
    {
        public Tbl_Prog_Test()
        {
            this.PerTestCaseResults = new HashSet<PerTestCaseResult>();
            this.Tbl_Prog_Ques = new HashSet<Tbl_Prog_Ques>();
            this.Tbl_Stud_ProgTest_TestCases = new HashSet<Tbl_Stud_ProgTest_TestCases>();
            this.Tbl_Stud_ProgTest_Details = new HashSet<Tbl_Stud_ProgTest_Details>();
        }
    
        public int Test_ID { get; set; }
        public string Test_Name { get; set; }
        public Nullable<int> Test_Duration { get; set; }
        public string Test_General_Info { get; set; }
        public Nullable<bool> Test_Lock { get; set; }
        public Nullable<bool> Test_IsActive { get; set; }
        public int Noofquestion { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<PerTestCaseResult> PerTestCaseResults { get; set; }
        public virtual ICollection<Tbl_Prog_Ques> Tbl_Prog_Ques { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_TestCases> Tbl_Stud_ProgTest_TestCases { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Details> Tbl_Stud_ProgTest_Details { get; set; }
    }
}
