//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Stud_ProgTest_Details
    {
        public int Stud_Detail_ID { get; set; }
        public int Stud_Test_ID { get; set; }
        public int Stud_ID { get; set; }
        public Nullable<int> Stud_Marks { get; set; }
        public int Stud_TestDuration { get; set; }
        public int Stud_Attempt_Ques { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Tbl_Prog_Test Tbl_Prog_Test { get; set; }
        public virtual user user { get; set; }
    }
}
