//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.SubTopics = new HashSet<SubTopic>();
        }
    
        public int TopicId { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<SubTopic> SubTopics { get; set; }
    }
}
