//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.ScoreDetails = new HashSet<ScoreDetail>();
            this.Tbl_Stud_ProgTest_Ans = new HashSet<Tbl_Stud_ProgTest_Ans>();
            this.Tbl_Stud_ProgTest_Ans1 = new HashSet<Tbl_Stud_ProgTest_Ans>();
            this.Tbl_Stud_ProgTest_Ans2 = new HashSet<Tbl_Stud_ProgTest_Ans>();
            this.Tbl_Stud_ProgTest_Ans3 = new HashSet<Tbl_Stud_ProgTest_Ans>();
            this.Tbl_Stud_ProgTest_Details = new HashSet<Tbl_Stud_ProgTest_Details>();
            this.Tbl_Stud_ProgTest_Result = new HashSet<Tbl_Stud_ProgTest_Result>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public int roleId { get; set; }
        public string RollNo { get; set; }
        public string Branch { get; set; }
        public string Mob { get; set; }
        public string Gender { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string CllgeName { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Ans> Tbl_Stud_ProgTest_Ans { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Ans> Tbl_Stud_ProgTest_Ans1 { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Ans> Tbl_Stud_ProgTest_Ans2 { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Ans> Tbl_Stud_ProgTest_Ans3 { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Details> Tbl_Stud_ProgTest_Details { get; set; }
        public virtual ICollection<Tbl_Stud_ProgTest_Result> Tbl_Stud_ProgTest_Result { get; set; }
    }
}
